-- E-commerce Database Schema
-- Run this SQL in phpMyAdmin or MySQL CLI


CREATE DATABASE ecommerce_db;
USE ecommerce_db;

-- Users Table
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    address TEXT DEFAULT NULL,
    role ENUM('customer', 'admin') DEFAULT 'customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Products Table
DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255) DEFAULT 'default.png',
    category VARCHAR(100) NOT NULL,
    stock INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Cart Table
DROP TABLE IF EXISTS cart;
CREATE TABLE cart (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Orders Table
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    status ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled') DEFAULT 'pending',
    shipping_address TEXT NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'cod',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Order Items Table
DROP TABLE IF EXISTS order_items;
CREATE TABLE order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Insert Admin User (password: admin123)
-- Hash generated by: password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO users (name, email, password, role) VALUES 
('Admin', 'admin@ecommerce.com', '$2y$10$rQZ8K1p/a0dL1LXMIgoEDFrOfMQbLgT4rM4C8YjU1i1cMq.GqQx.G3', 'admin');

-- OR run setup.php after importing to create admin user

-- Insert Sample Products
INSERT INTO products (name, description, price, image, category, stock) VALUES 
('Wireless Headphones', 'Premium wireless headphones with noise cancellation and 30-hour battery life.', 149.99, 'headphones.jpg', 'Electronics', 50),
('Smart Watch', 'Feature-rich smartwatch with heart rate monitor and GPS tracking.', 299.99, 'smartwatch.jpg', 'Electronics', 30),
('Laptop Stand', 'Ergonomic aluminum laptop stand with adjustable height.', 49.99, 'laptop_stand.jpg', 'Accessories', 100),
('Mechanical Keyboard', 'RGB mechanical keyboard with Cherry MX switches.', 129.99, 'keyboard.jpg', 'Electronics', 45),
('Wireless Mouse', 'Ergonomic wireless mouse with silent clicks.', 39.99, 'mouse.jpg', 'Accessories', 80),
('USB-C Hub', '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.', 59.99, 'usb_hub.jpg', 'Accessories', 60),
('Bluetooth Speaker', 'Portable Bluetooth speaker with 360-degree sound.', 79.99, 'speaker.jpg', 'Electronics', 40),
('Webcam HD', '1080p HD webcam with built-in microphone.', 89.99, 'webcam.jpg', 'Electronics', 35),
('Phone Case', 'Premium protective phone case with card slot.', 24.99, 'phone_case.jpg', 'Accessories', 200),
('Screen Protector', 'Tempered glass screen protector for smartphones.', 12.99, 'screen_protector.jpg', 'Accessories', 300),
('Tablet Stand', 'Adjustable tablet stand for desk or bed.', 34.99, 'tablet_stand.jpg', 'Accessories', 70),
('LED Desk Lamp', 'Touch-controlled LED desk lamp with dimming options.', 44.99, 'desk_lamp.jpg', 'Electronics', 55),
('Wireless Charger', 'Fast wireless charging pad compatible with all Qi devices.', 29.99, 'wireless_charger.jpg', 'Accessories', 120),
('Earbuds', 'True wireless earbuds with active noise cancellation.', 179.99, 'earbuds.jpg', 'Electronics', 65),
('External SSD', 'Portable 1TB external SSD with USB 3.2 connectivity.', 119.99, 'external_ssd.jpg', 'Electronics', 25),
('Gaming Chair', 'Ergonomic gaming chair with lumbar support.', 349.99, 'gaming_chair.jpg', 'Furniture', 15),
('Desk Organizer', 'Multi-compartment desk organizer for office supplies.', 27.99, 'desk_organizer.jpg', 'Accessories', 90),
('Monitor Arm', 'Adjustable monitor arm for dual monitor setup.', 89.99, 'monitor_arm.jpg', 'Accessories', 40),
('Cable Management Kit', 'Complete cable management solution for clean desk setup.', 19.99, 'cable_kit.jpg', 'Accessories', 150),
('Anti-Fatigue Mat', 'Ergonomic anti-fatigue mat for standing desks.', 39.99, 'anti_fatigue_mat.jpg', 'Furniture', 50);
